FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY apps/frontend/package.json ./
COPY apps/frontend/pnpm-lock.yaml ./

RUN pnpm install

COPY apps/frontend/ ./

RUN pnpm run build

FROM nginx:alpine

COPY --from=0 /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]