services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      - db
    command: >
      sh -c "
        until pg_isready -h db -p 5432; do
          echo 'Esperando o banco de dados ficar pronto...';
          sleep 2;
        done;
        npx prisma migrate dev &&
        npx prisma db seed &&
        node dist/src/main.js"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VITE_GOOGLE_API_KEY: ${VITE_GOOGLE_API_KEY}


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: