FROM node:20-alpine

RUN npm install -g pnpm

RUN apk add --no-cache postgresql-client

WORKDIR /usr/src/api

COPY apps/backend/package*.json ./
COPY apps/backend/tsconfig*.json ./
COPY apps/backend/prisma ./prisma/
COPY apps/backend/src ./src/

RUN pnpm install
RUN pnpm run build

CMD ["pnpm", "start:prod"]
